# Generated by Django 3.2.13 on 2022-07-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bars',
            options={'ordering': ['-sum_rate'], 'verbose_name': 'Бар', 'verbose_name_plural': 'Бары'},
        ),
        migrations.AlterField(
            model_name='bars',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='bars',
            name='average_check',
            field=models.PositiveSmallIntegerField(verbose_name='Средний чек'),
        ),
        migrations.AlterField(
            model_name='bars',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bars',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='bars',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bars',
            name='sum_rate',
            field=models.PositiveSmallIntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='bars',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bars',
            name='work_time',
            field=models.CharField(max_length=150, verbose_name='Время работы'),
        ),
    ]
